"""recommendation job関連

Revision ID: fd3edf4649ec
Revises: 837c132a4e6f
Create Date: 2026-06-21 11:19:03.360462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd3edf4649ec"
down_revision: Union[str, Sequence[str], None] = "837c132a4e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fairy_id", sa.Uuid(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("budget", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "calculating",
                "completed",
                "failed",
                name="recommendationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fairy_id"],
            ["fairies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("plans_owner_user_id_fkey"), "plans", type_="foreignkey")
    op.drop_column("plans", "owner_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans",
        sa.Column("owner_user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("plans_owner_user_id_fkey"), "plans", "users", ["owner_user_id"], ["id"]
    )
    op.drop_table("recommendation_jobs")
    # ### end Alembic commands ###
