"""色々追加した

Revision ID: 837c132a4e6f
Revises: c1eb4b2efd75
Create Date: 2026-06-21 11:05:01.445580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel が生成する AutoString 等の型解決のため


# revision identifiers, used by Alembic.
revision: str = "837c132a4e6f"
down_revision: Union[str, Sequence[str], None] = "c1eb4b2efd75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "activities", sa.Column("duration_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "activities",
        sa.Column("preference_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("activities", sa.Column("embeddings", sa.JSON(), nullable=True))
    op.add_column("fairies", sa.Column("embeddings", sa.JSON(), nullable=True))

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "UPDATE activities SET duration_minutes = 0 WHERE duration_minutes IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE activities SET embeddings = '[]'::json WHERE embeddings IS NULL"
        )
    )
    bind.execute(
        sa.text("UPDATE fairies SET embeddings = '[]'::json WHERE embeddings IS NULL")
    )

    op.alter_column("activities", "duration_minutes", nullable=False)
    op.alter_column("activities", "embeddings", nullable=False)
    op.alter_column("fairies", "embeddings", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fairies", "embeddings")
    op.drop_column("activities", "embeddings")
    op.drop_column("activities", "preference_text")
    op.drop_column("activities", "duration_minutes")
    op.drop_table("activity_reviews")
    # ### end Alembic commands ###
