"""add icon to users

Revision ID: 68434d7b40b7
Revises: 4670735f9021
Create Date: 2026-06-16 18:53:49.390747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel が生成する AutoString 等の型解決のため
from importlib.resources import files
from dicebear import Avatar, Style
from uuid import UUID


# revision identifiers, used by Alembic.
revision: str = "68434d7b40b7"
down_revision: Union[str, Sequence[str], None] = "4670735f9021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )

    bind = op.get_bind()
    users = bind.execute(sa.text("SELECT id FROM users")).fetchall()

    for user in users:
        icon = generate_icon(user.id)
        bind.execute(
            sa.text("UPDATE users SET icon = :icon WHERE id = :id"),
            {"icon": icon, "id": user.id},
        )

    op.alter_column("users", "icon", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "icon")
    # ### end Alembic commands ###


def generate_icon(user_id: UUID) -> str:
    style = Style.from_json(
        files("dicebear_styles").joinpath("identicon.json").read_text("utf-8")
    )

    avatar = Avatar(style, {"rowProbability": 100, "seed": str(user_id)})

    svg = avatar.to_string()
    return svg
