"""activityのownerをstoreからuserにした

Revision ID: 506379b87524
Revises: c6e903285422
Create Date: 2026-06-23 17:13:45.956098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "506379b87524"
down_revision: Union[str, Sequence[str], None] = "c6e903285422"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("owner_user_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        op.f("activities_owner_store_id_fkey"), "activities", type_="foreignkey"
    )
    op.create_foreign_key(None, "activities", "users", ["owner_user_id"], ["id"])
    op.drop_column("activities", "owner_store_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column("owner_store_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "activities", type_="foreignkey")
    op.create_foreign_key(
        op.f("activities_owner_store_id_fkey"),
        "activities",
        "stores",
        ["owner_store_id"],
        ["id"],
    )
    op.drop_column("activities", "owner_user_id")
    # ### end Alembic commands ###
