"""versionが壊れたので全部やり直し

Revision ID: 1de8345275b0
Revises: defd22ab357c
Create Date: 2026-06-26 00:10:53.036650

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1de8345275b0"
down_revision: Union[str, Sequence[str], None] = "defd22ab357c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
